packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@bufbuild/buf'
  - '@parcel/watcher'
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - nx
  - sharp
  - unrs-resolver
