/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FormIndexImport } from './routes/form/index'
import { Route as BlogIndexImport } from './routes/blog/index'
import { Route as FormServerActionImport } from './routes/form/server-action'
import { Route as FormBasicImport } from './routes/form/basic'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FormIndexRoute = FormIndexImport.update({
  id: '/form/',
  path: '/form/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRoute,
} as any)

const FormServerActionRoute = FormServerActionImport.update({
  id: '/form/server-action',
  path: '/form/server-action',
  getParentRoute: () => rootRoute,
} as any)

const FormBasicRoute = FormBasicImport.update({
  id: '/form/basic',
  path: '/form/basic',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/form/basic': {
      id: '/form/basic'
      path: '/form/basic'
      fullPath: '/form/basic'
      preLoaderRoute: typeof FormBasicImport
      parentRoute: typeof rootRoute
    }
    '/form/server-action': {
      id: '/form/server-action'
      path: '/form/server-action'
      fullPath: '/form/server-action'
      preLoaderRoute: typeof FormServerActionImport
      parentRoute: typeof rootRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof rootRoute
    }
    '/form/': {
      id: '/form/'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form/basic': typeof FormBasicRoute
  '/form/server-action': typeof FormServerActionRoute
  '/blog': typeof BlogIndexRoute
  '/form': typeof FormIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form/basic': typeof FormBasicRoute
  '/form/server-action': typeof FormServerActionRoute
  '/blog': typeof BlogIndexRoute
  '/form': typeof FormIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/form/basic': typeof FormBasicRoute
  '/form/server-action': typeof FormServerActionRoute
  '/blog/': typeof BlogIndexRoute
  '/form/': typeof FormIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/form/basic' | '/form/server-action' | '/blog' | '/form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form/basic' | '/form/server-action' | '/blog' | '/form'
  id:
    | '__root__'
    | '/'
    | '/form/basic'
    | '/form/server-action'
    | '/blog/'
    | '/form/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormBasicRoute: typeof FormBasicRoute
  FormServerActionRoute: typeof FormServerActionRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FormIndexRoute: typeof FormIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormBasicRoute: FormBasicRoute,
  FormServerActionRoute: FormServerActionRoute,
  BlogIndexRoute: BlogIndexRoute,
  FormIndexRoute: FormIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/form/basic",
        "/form/server-action",
        "/blog/",
        "/form/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/form/basic": {
      "filePath": "form/basic.tsx"
    },
    "/form/server-action": {
      "filePath": "form/server-action.tsx"
    },
    "/blog/": {
      "filePath": "blog/index.tsx"
    },
    "/form/": {
      "filePath": "form/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
