import "./global.css";

import { TRPCReactProvider } from "@repo/protocol/trpc/react";

export const metadata = {
  title: "Welcome to othi",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
