import "./global.css";

import { GeistSans } from "geist/font/sans";
import { TRPCReactProvider } from "@repo/protocol/trpc/react";
import { cn } from "@repo/lib";

export const metadata = {
  title: "Welcome to othi",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(GeistSans.className)}>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
