// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file types/build.proto (package types.build, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/build.proto.
 */
export const file_types_build: GenFile = /*@__PURE__*/
  fileDesc("ChF0eXBlcy9idWlsZC5wcm90bxILdHlwZXMuYnVpbGQimgIKC0J1aWxkQ29uZmlnEiQKBGtpbmQYASABKA4yFi50eXBlcy5idWlsZC5CdWlsZEtpbmQSOgoNc2NyaXB0X2NvbmZpZxgCIAEoCzIeLnR5cGVzLmJ1aWxkLlNjcmlwdEJ1aWxkQ29uZmlnSACIAQESOgoNZG9ja2VyX2NvbmZpZxgDIAEoCzIeLnR5cGVzLmJ1aWxkLkRvY2tlckJ1aWxkQ29uZmlnSAGIAQESOAoMY2FyZ29fY29uZmlnGAQgASgLMh0udHlwZXMuYnVpbGQuQ2FyZ29CdWlsZENvbmZpZ0gCiAEBQhAKDl9zY3JpcHRfY29uZmlnQhAKDl9kb2NrZXJfY29uZmlnQg8KDV9jYXJnb19jb25maWciNgoQQ2FyZ29CdWlsZENvbmZpZxIVCghiaW5fbmFtZRgBIAEoCUgAiAEBQgsKCV9iaW5fbmFtZSI3ChFTY3JpcHRCdWlsZENvbmZpZxIVCghiaW5fbmFtZRgBIAEoCUgAiAEBQgsKCV9iaW5fbmFtZSInChFEb2NrZXJCdWlsZENvbmZpZxISCgppc19jb21wb3NlGAEgASgIKi4KCUJ1aWxkS2luZBIKCgZTY3JpcHQQABIKCgZEb2NrZXIQARIJCgVDYXJnbxACYgZwcm90bzM");

/**
 * @generated from message types.build.BuildConfig
 */
export type BuildConfig = Message<"types.build.BuildConfig"> & {
  /**
   * @generated from field: types.build.BuildKind kind = 1;
   */
  kind: BuildKind;

  /**
   * @generated from field: optional types.build.ScriptBuildConfig script_config = 2;
   */
  scriptConfig?: ScriptBuildConfig;

  /**
   * @generated from field: optional types.build.DockerBuildConfig docker_config = 3;
   */
  dockerConfig?: DockerBuildConfig;

  /**
   * @generated from field: optional types.build.CargoBuildConfig cargo_config = 4;
   */
  cargoConfig?: CargoBuildConfig;
};

/**
 * Describes the message types.build.BuildConfig.
 * Use `create(BuildConfigSchema)` to create a new message.
 */
export const BuildConfigSchema: GenMessage<BuildConfig> = /*@__PURE__*/
  messageDesc(file_types_build, 0);

/**
 * @generated from message types.build.CargoBuildConfig
 */
export type CargoBuildConfig = Message<"types.build.CargoBuildConfig"> & {
  /**
   * @generated from field: optional string bin_name = 1;
   */
  binName?: string;
};

/**
 * Describes the message types.build.CargoBuildConfig.
 * Use `create(CargoBuildConfigSchema)` to create a new message.
 */
export const CargoBuildConfigSchema: GenMessage<CargoBuildConfig> = /*@__PURE__*/
  messageDesc(file_types_build, 1);

/**
 * @generated from message types.build.ScriptBuildConfig
 */
export type ScriptBuildConfig = Message<"types.build.ScriptBuildConfig"> & {
  /**
   * @generated from field: optional string bin_name = 1;
   */
  binName?: string;
};

/**
 * Describes the message types.build.ScriptBuildConfig.
 * Use `create(ScriptBuildConfigSchema)` to create a new message.
 */
export const ScriptBuildConfigSchema: GenMessage<ScriptBuildConfig> = /*@__PURE__*/
  messageDesc(file_types_build, 2);

/**
 * @generated from message types.build.DockerBuildConfig
 */
export type DockerBuildConfig = Message<"types.build.DockerBuildConfig"> & {
  /**
   * @generated from field: bool is_compose = 1;
   */
  isCompose: boolean;
};

/**
 * Describes the message types.build.DockerBuildConfig.
 * Use `create(DockerBuildConfigSchema)` to create a new message.
 */
export const DockerBuildConfigSchema: GenMessage<DockerBuildConfig> = /*@__PURE__*/
  messageDesc(file_types_build, 3);

/**
 * @generated from enum types.build.BuildKind
 */
export enum BuildKind {
  /**
   * @generated from enum value: Script = 0;
   */
  Script = 0,

  /**
   * @generated from enum value: Docker = 1;
   */
  Docker = 1,

  /**
   * @generated from enum value: Cargo = 2;
   */
  Cargo = 2,
}

/**
 * Describes the enum types.build.BuildKind.
 */
export const BuildKindSchema: GenEnum<BuildKind> = /*@__PURE__*/
  enumDesc(file_types_build, 0);

