name: webapp
env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
      OAUTH_OTHI_GITHUB_ID: ${{secrets.OAUTH_OTHI_GITHUB_ID}}
      OAUTH_OTHI_GITHUB_SECRET: ${{secrets.OAUTH_OTHI_GITHUB_SECRET}}
      OAUTH_GITHUB_SUDO_IDENT: ${{secrets.OAUTH_GITHUB_SUDO_IDENT}}
      DB_URL: ${{secrets.DB_URL}}
      DB_AUTH_TOKEN: ${{secrets.DB_AUTH_TOKEN}}
      UPLOADTHING_TOKEN: ${{secrets.UPLOADTHING_TOKEN}}
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: install dependencies
        run: |
          pnpm config set "@tiptap-pro:registry" https://registry.tiptap.dev/
          pnpm config set "//registry.tiptap.dev/:_authToken" ${{secrets.TIPTAP_PRO_TOKEN}}
          pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: pnpm exec nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - run: pnpm exec nx affected -t lint test build
