// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file repo.proto (package repo, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Service } from "./service_pb";
import { file_service } from "./service_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file repo.proto.
 */
export const file_repo: GenFile = /*@__PURE__*/
  fileDesc("CgpyZXBvLnByb3RvEgRyZXBvIiUKDEJ1aWxkUmVxdWVzdBIVCg1zZXJ2aWNlX25hbWVzGAEgAygJIh8KDUJ1aWxkUmVzcG9uc2USDgoGc3RhdHVzGAEgASgJIjMKEFJlcG9MaXN0UmVzcG9uc2USHwoFcmVwb3MYASADKAsyEC5zZXJ2aWNlLlNlcnZpY2UydgoKUmVwb0FjdGlvbhI2CgRMaXN0EhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhYucmVwby5SZXBvTGlzdFJlc3BvbnNlEjAKBUJ1aWxkEhIucmVwby5CdWlsZFJlcXVlc3QaEy5yZXBvLkJ1aWxkUmVzcG9uc2ViBnByb3RvMw", [file_google_protobuf_empty, file_service]);

/**
 * @generated from message repo.BuildRequest
 */
export type BuildRequest = Message<"repo.BuildRequest"> & {
  /**
   * @generated from field: repeated string service_names = 1;
   */
  serviceNames: string[];
};

/**
 * Describes the message repo.BuildRequest.
 * Use `create(BuildRequestSchema)` to create a new message.
 */
export const BuildRequestSchema: GenMessage<BuildRequest> = /*@__PURE__*/
  messageDesc(file_repo, 0);

/**
 * @generated from message repo.BuildResponse
 */
export type BuildResponse = Message<"repo.BuildResponse"> & {
  /**
   * @generated from field: string status = 1;
   */
  status: string;
};

/**
 * Describes the message repo.BuildResponse.
 * Use `create(BuildResponseSchema)` to create a new message.
 */
export const BuildResponseSchema: GenMessage<BuildResponse> = /*@__PURE__*/
  messageDesc(file_repo, 1);

/**
 * @generated from message repo.RepoListResponse
 */
export type RepoListResponse = Message<"repo.RepoListResponse"> & {
  /**
   * @generated from field: repeated service.Service repos = 1;
   */
  repos: Service[];
};

/**
 * Describes the message repo.RepoListResponse.
 * Use `create(RepoListResponseSchema)` to create a new message.
 */
export const RepoListResponseSchema: GenMessage<RepoListResponse> = /*@__PURE__*/
  messageDesc(file_repo, 2);

/**
 * @generated from service repo.RepoAction
 */
export const RepoAction: GenService<{
  /**
   * @generated from rpc repo.RepoAction.List
   */
  list: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof RepoListResponseSchema;
  },
  /**
   * Build a service(s).
   * Default to building all if no service is provided
   *
   * @generated from rpc repo.RepoAction.Build
   */
  build: {
    methodKind: "unary";
    input: typeof BuildRequestSchema;
    output: typeof BuildResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_repo, 0);

