// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file service.proto (package service, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { DeploymentKind } from "./types/deployment_pb";
import { file_types_deployment } from "./types/deployment_pb";
import type { BuildConfig } from "./types/build_pb";
import { file_types_build } from "./types/build_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service.proto.
 */
export const file_service: GenFile = /*@__PURE__*/
  fileDesc("Cg1zZXJ2aWNlLnByb3RvEgdzZXJ2aWNlIjkKE1NlcnZpY2VMaXN0UmVzcG9uc2USIgoIc2VydmljZXMYASADKAsyEC5zZXJ2aWNlLlNlcnZpY2Ui2wEKB1NlcnZpY2USFAoMc2VydmljZV9uYW1lGAEgASgJEgsKA3VybBgCIAEoCRISCgVfcGF0aBgDIAEoCUgAiAEBEjkKCmRlcGxveW1lbnQYBCABKA4yIC50eXBlcy5kZXBsb3ltZW50LkRlcGxveW1lbnRLaW5kSAGIAQESLgoMYnVpbGRfY29uZmlnGAUgASgLMhgudHlwZXMuYnVpbGQuQnVpbGRDb25maWcSFQoNcmVsYXRpdmVfcm9vdBgGIAEoCUIICgZYX3BhdGhCDQoLX2RlcGxveW1lbnQyTQoNU2VydmljZUFjdGlvbhI8CgRMaXN0EhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5Ghwuc2VydmljZS5TZXJ2aWNlTGlzdFJlc3BvbnNlYgZwcm90bzM", [file_google_protobuf_empty, file_types_deployment, file_types_build]);

/**
 * @generated from message service.ServiceListResponse
 */
export type ServiceListResponse = Message<"service.ServiceListResponse"> & {
  /**
   * @generated from field: repeated service.Service services = 1;
   */
  services: Service[];
};

/**
 * Describes the message service.ServiceListResponse.
 * Use `create(ServiceListResponseSchema)` to create a new message.
 */
export const ServiceListResponseSchema: GenMessage<ServiceListResponse> = /*@__PURE__*/
  messageDesc(file_service, 0);

/**
 * @generated from message service.Service
 */
export type Service = Message<"service.Service"> & {
  /**
   * @generated from field: string service_name = 1;
   */
  serviceName: string;

  /**
   * @generated from field: string url = 2;
   */
  url: string;

  /**
   * @generated from field: optional string _path = 3;
   */
  Path?: string;

  /**
   * @generated from field: optional types.deployment.DeploymentKind deployment = 4;
   */
  deployment?: DeploymentKind;

  /**
   * @generated from field: types.build.BuildConfig build_config = 5;
   */
  buildConfig?: BuildConfig;

  /**
   * @generated from field: string relative_root = 6;
   */
  relativeRoot: string;
};

/**
 * Describes the message service.Service.
 * Use `create(ServiceSchema)` to create a new message.
 */
export const ServiceSchema: GenMessage<Service> = /*@__PURE__*/
  messageDesc(file_service, 1);

/**
 * @generated from service service.ServiceAction
 */
export const ServiceAction: GenService<{
  /**
   * rpc Deploy (Foo) returns (Service);
   *
   * @generated from rpc service.ServiceAction.List
   */
  list: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof ServiceListResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_service, 0);

